name: 'Find and close milestone'
description: 'Find the milestone by a release tag, close it and notify all related issues'
inputs:
  token:
    required: true
    description: 'token with access to your repository'
  releaseTag:
    required: true
    description: "released version's tag"
runs:
  using: 'node16'
  main: 'dist/index.js'
