version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'VKCOM/vk-sec'
      - 'VKCOM/vkui-core'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'direct'
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      jest:
        patterns:
          - 'jest'
          - '@jest/*'
    reviewers:
      - 'VKCOM/vk-sec'
      - 'VKCOM/vkui-core'
