version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'direct'
    groups:
      jest:
        patterns:
          - 'jest*'
          - '@jest/*'
          - '@swc/jest'
      eslint:
        patterns:
          - 'eslint*'
          - '@vkontakte/eslint-plugin'
          - '@typescript-eslint/*'
      prettier:
        patterns:
          - 'prettier'
          - '@vkontakte/prettier-config'
