name: 'Add Milestone to PR'
description: 'Adds the next minor version milestone to Dependabot PRs for specific dependencies'
inputs:
  token:
    required: true
    description: 'token with access to your repository'

  pull_request_number:
    required: true
    description: 'pull request number to add milestone'
runs:
  using: 'node20'
  main: 'index.js'