name: 'Node.js up PR'
description: 'Create PR with up Node.js version'
inputs:
  token:
    required: true
    description: 'token with access to your repository'

runs:
  using: "composite"
  steps:
    - name: Run update version
      run: curl -s https://nodejs.org/dist/index.json | jq 'max_by(.version | ltrimstr("v") | split(".") | map(tonumber)) | .version' -r > .nvmrc
      shell: bash

    - name: Get version
      id: version
      run: echo "VERSION=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Create Pull Request
      uses: ./shared/create-pr
      with:
        token: ${{ inputs.token }}
        branch: github-actions/build/tools/nvm-up
        commit-message: 'build(tools): Node.js version update to ${{ steps.version.outputs.VERSION }}'
        title: 'Node.js version update to ${{ steps.version.outputs.VERSION }}'
        body: |
          Automated Node.js version update to [${{ steps.version.outputs.VERSION }}](https://nodejs.org/en/blog/release/${{ steps.version.outputs.VERSION }})

          ## Release notes
          -
        add-paths: .nvmrc
