name: 'Find and close milestone/Publish the Release Notes'
description: 'Find and close the milestone, notify all related issues and publish the release notes'
inputs:
  token:
    required: true
    description: 'token with access to your repository'
  releaseTag:
    required: true
    description: "released version's tag"
runs:
  using: 'node16'
  main: 'dist/index.js'
