name: 'Corepack up PR'
description: 'Create PR with corepack up'
inputs:
  token:
    required: true
    description: 'token with access to your repository'

runs:
  using: "composite"
  steps:
    - name: Run corepack up
      run: corepack up
      shell: bash
      env:
        YARN_ENABLE_IMMUTABLE_INSTALLS: false

    - name: Create Pull Request
      uses: ./shared/create-pr
      with:
        token: ${{ inputs.token }}
        branch: github-actions/build/tools/corepack-up
        commit-message: 'build(tools): corepack up'
        title: 'Corepack up'
        body: |
          Automated corepack up

          ## Release notes
          -
