name: 'Find actual milestone'
description: 'Find the actual milestone for publishing package'
inputs:
  token:
    required: true
    description: 'token with access to your repository'
runs:
  using: 'node16'
  main: 'dist/index.js'
