name: 'Update release notes'
description: 'Auto update release notes'
inputs:
  pull_request_number:
    required: true
    description: 'pull request number'

  token:
    required: true
    description: 'token with access to your repository'
runs:
  using: 'node24'
  main: 'dist/index.js'
