name: 'Patch'
description: 'GitLab Flow create patch'
inputs:
  token:
    required: true
    description: 'token with access to your repository'
  directory:
    required: false
    description: 'main directory of your project (default is your root directory)'
  targetBranch:
    required: false
    description: 'target of your project (default is stable branch)'
  needScreenshots:
    required: false
    description: 'include screenshots in a patch (default ignore screenshots)'
runs:
  using: 'node16'
  main: 'dist/index.js'
