name: 'Main'

on:
  push:
    branches:
      - main

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    name: Build main
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.DEVTOOLS_GITHUB_TOKEN }}

      - name: Enable Corepack
        run: corepack enable
        shell: bash
  
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          # Кэш может быть отравлен, поэтому не используем его
  
      - name: Install dependencies
        run: YARN_ENABLE_SCRIPTS=false yarn install --immutable --check-cache --check-resolutions
        shell: bash

      - name: Run Building
        run: yarn run build

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'build(actions): update dist'
